from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime
from enum import Enum
from .action_step import ActionStep  # Import after creating ActionStep


class ActionSequenceStatus(str, Enum):
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class ActionSequence(BaseModel):
    """
    Represents a sequence of actions generated by the LLM from a voice command.
    """
    id: str
    voice_command_id: str
    sequence: List[ActionStep] = Field(..., min_items=1)
    description: str
    status: ActionSequenceStatus = ActionSequenceStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.now)
    executed_at: Optional[datetime] = None

    def execute(self):
        """
        Mark the action sequence as in progress.
        """
        self.status = ActionSequenceStatus.IN_PROGRESS

    def complete(self):
        """
        Mark the action sequence as completed.
        """
        self.status = ActionSequenceStatus.COMPLETED
        self.executed_at = datetime.now()

    def fail(self):
        """
        Mark the action sequence as failed.
        """
        self.status = ActionSequenceStatus.FAILED
        self.executed_at = datetime.now()


# Example usage:
if __name__ == "__main__":
    import uuid
    from .action_step import ActionStep, ActionType

    action_step = ActionStep(
        id=str(uuid.uuid4()),
        action_sequence_id=str(uuid.uuid4()),
        action_type=ActionType.NAVIGATION,
        parameters={"x": 1.0, "y": 2.0, "theta": 0.0},
        timeout=10,
        order=0
    )

    action_seq = ActionSequence(
        id=str(uuid.uuid4()),
        voice_command_id=str(uuid.uuid4()),
        sequence=[action_step],
        description="Move robot to specified coordinates"
    )

    print(action_seq.json(indent=2))