# This file is required for Python to treat the directory as a package
# ROS message definitions would typically be auto-generated from .msg files
# For this example, we'll just document what messages should exist
"""
ROS Message Definitions for VLA Capstone Project

This package contains message definitions for the Voice-Language-Action (VLA) system.
These would typically be defined in .msg files and auto-generated by ROS.

Expected message types:
- VoiceCommand.msg
- ActionSequence.msg
- VoiceCommandResponse.msg
- VLASystemState.msg
"""